# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198AFLuXzokoK2xI8eCiitmizOjSwuHv5
"""

import pandas as pd
from fincaprueba import fincaraiz
from metrocuadrado import metrocuadrado
from realityserver import realityserver
from lonja import lonja

def scrap_total():

    data_historica=pd.read_csv("data_contatenada.csv", sep=',')

    #EXTRAER DATA WEB SCRAPP
    df1=fincaraiz()
    df2=metrocuadrado()
    df3=realityserver()
    df4=lonja()
    
    #CONCATENAR DATA

    data_historica=pd.concat([data_historica,df1,df2,df3, df4])
    data_historica.drop_duplicates(['idpropiedad'], inplace=True)
    data_historica.reset_index(drop=True, inplace=True)

    data_historica["tipopropiedad"]=data_historica["tipopropiedad"].str.strip()

    data_historica.to_csv("data_contatenada.csv", index=False)

    return data_historica